name: Mirror GitHub Selected Repos to Gitee

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Mirror Github to Gitee with white list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/yakir3
        dst: gitee/yakir
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: 'cncf-record,yakir3.github.io,Tools,environment,picProject'
        force_update: true
