name: Sync Multiple Repos to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: '0 03 */7 * *'
 
jobs:
  sync_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [dockerfiles, flask-demo, gitbook]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone https://yakir3:${GH_TOKEN}@github.com/yakir3/${{ matrix.repo }}.git && cd ${{ matrix.repo }}
          git remote add gitlab https://yakir357:${GITLAB_TOKEN}@gitlab.com/yakir357/${{ matrix.repo }}.git
          git push gitlab main --force
          cd
