name: Sync GitHub Repos to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: '0 03 */15 * *'
 
jobs:
  sync_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [dockerfiles,environment,flask-demo,gitbook,github-sync-action,helm-charts,jiracdflow,optimus,pic-tools,private-env,yakir3,yakir3.github.io]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git clone https://yakir3:${GH_TOKEN}@github.com/yakir3/${{ matrix.repo }}.git && cd ${{ matrix.repo }}
          git config http.postBuffer 524288000
          git remote add gitlab https://yakir357:${GITLAB_TOKEN}@gitlab.com/yakir357/${{ matrix.repo }}.git
          git push gitlab main --force
          cd
